---
skip_tags: true

cache:
  - C:\strawberry -> appveyor.yml
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

install:
  #- git submodule update --init --recursive --quiet
  - IF NOT EXIST "C:\strawberry" cinst strawberryperl
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - cpanm Dist::Zilla --notest
  - dzil authordeps --missing | cpanm --notest
  - dzil listdeps --author --missing | cpanm --notest

build: off

test_script:
- dzil test -v
