name: Build
 
on:
  push:
    braches:
      - master
  pull_request:
    braches:
      - master
 
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        perl: ['5.36', '5.32', '5.26']
        exclude:
          - os: windows-latest
            perl: '5.36'
          - os: windows-latest
            perl: '5.26'
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up perl
      uses: shogo82148/actions-setup-perl@v1
      with:
          perl-version: ${{ matrix.perl }}
          distribution: ${{ (startsWith(matrix.os, 'windows') && 'strawberry' ) || 'default' }}
 
    - run: perl -V

    - name: Install Dist::Zilla
      run: cpanm --notest Dist::Zilla

    - name: Install authordeps
      run: dzil authordeps --missing | cpanm --notest
 
    - name: Run tests
      run: dzil test
